appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NlGV2I5mrE8ZeX4+FpunJHfnyMJzbRTZXcjWN8jwWice+ugfn/LoSDPAqI27CZCxOivd477RmXmYlM9tSFScjDw6cHVheTxMaIs8zVoOucF551cffG7vTYhFw+ChbCc642+xVD9orf0f2rTmphyITfXTYbbD7cSEOf1SNzq/2PC+yS47+yeVXjcI5/MUttfEHGx/PCJlMH6w81hXXtzasSuj5p8EOIZEqgp8raXzCjX8GGhRKtdLl68zIrFrwz7Y7tZuK/11uD+EhhksPWhbd97MYLp93MUrxj/tbf1C4Di9wg3xEwPP2Xyx6U8XRWPlinh4HNen5VKpeeakzy+4Up45UPN18pa3XHrsrUb85Q+TKXjtdfW2WIjwhBmlEYVb+lBEAD8pzpCDGiM0Rpc+5mr9PoM3jkcSY6p8ARCkpOgDXx3t0q8eUkDzBW/fi9FQRrvozAoakGhzl0a6fSxBuzvElwxCmy2MnfRB4Wum4rNZBjfALxdPPm/6fEm5AkvxBZELBvZ4J6N8UbdfzD9L7NLqO2EYNWNoO3jzhMkzahK4w5BCaxq5/NkXzca6TEp4mvnT72ebcnkJs09tH90CVUmfIEcTyucIaHvrYu7OjawSRDDuaNVIyNXIvL8WnIYZwQgohbRaiW9f180JoVkl/P+pYOCwPmo0THSdY9G9K+w=
conda_forge_output_validation: true
